FROM tily/niftycloud-computing-cli
RUN apt-get update -y && apt-get install -y vim
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y nodejs
RUN npm install -g hubot coffee-script
WORKDIR /usr/local/bot
